import mongoose, { Schema } from 'mongoose';

const SocialAccountSchema = new Schema({
  id: { type: String, required: true },
  platform: { type: String, required: true },
  username: { type: String, default: '' },
  displayName: { type: String, default: '' },
  profileDir: { type: String, default: '' },
  accountIndex: { type: Number, default: 0 },
  addedAt: { type: String, default: () => new Date().toISOString() },
  active: { type: Boolean, default: true },
}, { _id: false });

const SettingsSchema = new Schema({
  userId: { type: String, unique: true, index: true, sparse: true },
  companyName: { type: String, default: '' },
  companyDescription: { type: String, default: '' },
  keywords: [{ type: String }],
  platforms: [{ type: String, enum: ['twitter', 'reddit', 'facebook', 'quora', 'youtube', 'pinterest'] }],
  subreddits: [{ type: String }],
  promptTemplate: { type: String, default: '' },
  socialAccounts: { type: [SocialAccountSchema], default: [] },
  facebookGroups: [{ type: String }],
  facebookKeywords: [{ type: String }],
  facebookDailyLimit: { type: Number, default: 5 },
  facebookAutoPostThreshold: { type: Number, default: 70 },
  facebookBrandMentionRate: { type: Number, default: 25, min: 0, max: 100 },
  facebookCooldownMinutes: { type: Number, default: 90, min: 30 },
  twitterKeywords: [{ type: String }],
  twitterCommunityIds: [{ type: String }],
  twitterDailyLimit: { type: Number, default: 10 },
  twitterAutoPostThreshold: { type: Number, default: 70 },
  twitterBrandMentionRate: { type: Number, default: 25, min: 0, max: 100 },
  twitterCooldownMinutes: { type: Number, default: 60, min: 15 },
  twitterOriginalTweetsEnabled: { type: Boolean, default: false },
  twitterOriginalTweetDailyLimit: { type: Number, default: 2 },
  twitterTweetTopics: [{ type: String }],
  twitterTweetPersona: { type: String, default: '' },
  twitterTweetStyles: [{ type: String }],
  twitterLikeRate: { type: Number, default: 70, min: 0, max: 100 },
  twitterRetweetRate: { type: Number, default: 10, min: 0, max: 100 },
  twitterBookmarkRate: { type: Number, default: 8, min: 0, max: 100 },
  twitterReplyRate: { type: Number, default: 60, min: 0, max: 100 },
  redditKeywords: [{ type: String }],
  redditDailyLimit: { type: Number, default: 5 },
  redditAutoPostThreshold: { type: Number, default: 70 },
  redditBrandMentionRate: { type: Number, default: 25, min: 0, max: 100 },
  redditCooldownMinutes: { type: Number, default: 90, min: 30 },
  quoraKeywords: [{ type: String }],
  quoraDailyLimit: { type: Number, default: 3 },
  quoraAutoPostThreshold: { type: Number, default: 70 },
  quoraBrandMentionRate: { type: Number, default: 25, min: 0, max: 100 },
  quoraCooldownMinutes: { type: Number, default: 120, min: 60 },
  youtubeKeywords: [{ type: String }],
  youtubeDailyLimit: { type: Number, default: 5 },
  youtubeAutoPostThreshold: { type: Number, default: 70 },
  youtubeBrandMentionRate: { type: Number, default: 25, min: 0, max: 100 },
  youtubeCooldownMinutes: { type: Number, default: 180, min: 90 },
  pinterestKeywords: [{ type: String }],
  pinterestDailyLimit: { type: Number, default: 5 },
  pinterestAutoPostThreshold: { type: Number, default: 70 },
  pinterestBrandMentionRate: { type: Number, default: 25, min: 0, max: 100 },
  pinterestCooldownMinutes: { type: Number, default: 90, min: 30 },
  autoPostingPaused: { type: Boolean, default: false },
  cronTimezone: { type: String, default: '' },
  cronStartHour: { type: Number, default: 9 },
  cronEndHour: { type: Number, default: 18 },
  cronDays: { type: [Number], default: [0, 1, 2, 3, 4, 5, 6] },
  cronIntervalMinutes: { type: Number, default: 15, min: 15, max: 360 },
  lastCronRunAt: { type: Date, default: null },
  isAdmin: { type: Boolean, default: false },
  blockedUntil: { type: Date, default: null },
  // Notification preferences
  notificationEmail: { type: String, default: '' },
  notifyViaEmail: { type: Boolean, default: true },
  lastNotificationEmailSentAt: { type: Date, default: null },
}, { timestamps: true });

// Index for cron scheduler query: find active users not paused
SettingsSchema.index({ autoPostingPaused: 1, userId: 1 });

export default mongoose.models.Settings || mongoose.model('Settings', SettingsSchema);
